### PR TITLE
Multilingual Support for Rehabify

### LINKED ISSUE #70: [FEAT]: AddingMulti-language Support in Rehabify
### Description:
We need to integrate Google Translator into the Rehabify web application to allow users to translate all pages into multiple languages. This will enhance the user experience for non-English-speaking users by providing them with an accessible interface in their preferred language.

### Tasks:

	1.	Investigate the Google Translator API or other suitable translation tools.
	2.	Integrate the translator into the main layout of the application.
	3.	Ensure translation is available for all pages
	4.	Add a language selector dropdown to the header/footer for easy language switching.
	5.	Test translations to ensure proper formatting and layout across all languages.

### Acceptance Criteria:

	•	Users should be able to translate any page to their selected language using the Google Translator integration.
	•	The layout and styling of pages should not break when the content is translated.
	•	The language selector should be accessible and functional on all pages.

### Program: GSSOC-ext and hacktoberfest
** Please add LEVEL 3 to the issue**

### PR DESCRIPTION
**Pull request by IkkiOcean**
## Description:

This PR introduces multilingual support to the Rehabify application, enhancing accessibility and user experience for a diverse user base. Users can now select their preferred language from a newly implemented language dropdown, allowing them to interact with the application in their native language. 

**Related Issues:**
- Closes #70 

## Key Changes

1. **Google Translate Component:**
   - Introduced a new `GoogleTranslate` component that initializes the Google Translate widget on the application.
   - Users can select from a wide range of languages, including English, Hindi, Punjabi, Spanish, Japanese, and more.

2. **Dynamic Script Loading:**
   - The Google Translate script is loaded dynamically, ensuring that it only loads when the component is mounted.
   - Implemented a retry mechanism to handle script loading errors.

3. **Custom Styling:**
   - Added custom CSS styles for the Google Translate dropdown to ensure consistency with the application's design.
   - Included styles for hover effects, button appearance, and hiding unnecessary elements from Google’s branding.

4. **Text Cleanup:**
   - Implemented a cleanup function to clear text from the Google Translate gadget for a cleaner user interface.

5. **TypeScript Support:**
   - Used TypeScript with appropriate type declarations for the global `window` object, ensuring better type safety and IDE support.

## Benefits

- This feature will allow Rehabify to cater to a broader audience, enhancing the inclusivity of the application.
- Users will experience a more personalized interaction, improving their overall engagement with the platform.

## Video: 

https://github.com/user-attachments/assets/88969bc1-75ff-47f7-853f-1da4dde8fffb

**Additional Notes:**
- Future work may include adding support for additional languages based on user feedback and demand.

### CODE REVIEW

**Comment by IkkiOcean** [comment]
Please tag level 3 for this feature

**Comment by ratnesh-maurya** [comment]
> Please tag level 3 for this feature

Can to try to fit the select language in the leader and make the ui such that it matches the existing theme button and setting icon .

This issue can be assigned as level 2 .

**Comment by IkkiOcean** [comment]
> > Please tag level 3 for this feature
> 
> Can to try to fit the select language in the leader and make the ui such that it matches the existing theme button and setting icon .
> 
> This issue can be assigned as level 2 .

can you brief it a little? i can change the ui of select option to fit more better, is that what you want?

**Comment by ratnesh-maurya** [comment]
> > > Please tag level 3 for this feature
> > 
> > 
> > Can to try to fit the select language in the leader and make the ui such that it matches the existing theme button and setting icon .
> > This issue can be assigned as level 2 .
> 
> can you brief it a little? i can change the ui of select option to fit more better, is that what you want?

yes and place it in the header where the theme toggle button is

**Comment by IkkiOcean** [comment]
> > > > Please tag level 3 for this feature
> > > 
> > > 
> > > Can to try to fit the select language in the leader and make the ui such that it matches the existing theme button and setting icon .
> > > This issue can be assigned as level 2 .
> > 
> > 
> > can you brief it a little? i can change the ui of select option to fit more better, is that what you want?
> 
> yes and place it in the header where the theme toggle button is

I wont recommend adding this to the top of the page. This feature is usually provided in footer so it doesnt disturb elements on the header. Not everyone would want to translate the page like they want the dark mode

**Comment by ratnesh-maurya** [comment]
> > > > > Please tag level 3 for this feature
> > > > 
> > > > 
> > > > Can to try to fit the select language in the leader and make the ui such that it matches the existing theme button and setting icon .
> > > > This issue can be assigned as level 2 .
> > > 
> > > 
> > > can you brief it a little? i can change the ui of select option to fit more better, is that what you want?
> > 
> > 
> > yes and place it in the header where the theme toggle button is
> 
> I wont recommend adding this to the top of the page. This feature is usually provided in footer so it doesnt disturb elements on the header. Not everyone would want to translate the page like they want the dark mode

i didnt saw it in the footer using it is available at top of page 

{1DBD1BBB-D906-4A32-B660-C3E80E0028A6}

you can implement something like this if you want

**Comment by IkkiOcean** [comment]
> > > > > > Please tag level 3 for this feature
> > > > > 
> > > > > 
> > > > > Can to try to fit the select language in the leader and make the ui such that it matches the existing theme button and setting icon .
> > > > > This issue can be assigned as level 2 .
> > > > 
> > > > 
> > > > can you brief it a little? i can change the ui of select option to fit more better, is that what you want?
> > > 
> > > 
> > > yes and place it in the header where the theme toggle button is
> > 
> > 
> > I wont recommend adding this to the top of the page. This feature is usually provided in footer so it doesnt disturb elements on the header. Not everyone would want to translate the page like they want the dark mode
> 
> i didnt saw it in the footer using it is available at top of page
> 
> {1DBD1BBB-D906-4A32-B660-C3E80E0028A6}
> 
> you can implement something like this if you want
> 
> https://preview.themeforest.net/item/elstar-react-tailwind-admin-template/full_screen_preview/39768117?_ga=2.124699594.1904153165.1728580424-1415098213.1728580424&_gac=1.91506408.1728580424.CjwKCAjw9p24BhB_EiwA8ID5Bpk_PzmcTd97bGvv2q5P_o5DN5aJW7rLhOsVBlHZE0rf9FZZ30HMpBoCbVcQAvD_BwE

After our discussion, I explored several methods to implement your request but realized it's not possible without a paid option. The Google Cloud API is a paid service, and the method I'm using is limited to the development phase and very little customisable by the google. Since the Google Translate widget is no longer available, you would need to rely on Google's paid Cloud Translation API for machine translation. This requires a Google Cloud account and several installation steps to activate the Cloud Translation API and integrate it into your site.

**Comment by ratnesh-maurya** [comment]
okay , i will see for now its good to go

**Review by ratnesh-maurya — APPROVED** [review]

**Pull request merged**
