### PR TITLE
Dockerize backend #133

### PR DESCRIPTION
**Pull request by sanjay14073**
Dockerized the backend.Now with docker-compose up command and docker installed in a devs system,they can run the backend.
They dont need to have the go or mongodb installed on their system.

### CODE REVIEW

**Comment by ratnesh-maurya** [comment]
Busy in some work will review it Tomorrow

**Comment by ratnesh-maurya** [comment]
just a small improvement , we don't have migration file written so there is no need of setting mongo container , it will be supplied on runtime and make sure environment variable can be supplied on runtime also add a documentation for the same so that newie can also start the  container

**Comment by sanjay14073** [comment]
@ratnesh-maurya sure will do it tomorrow

**Comment by sanjay14073** [comment]
@ratnesh-maurya done with required changes could you review it once

**Review by ratnesh-maurya — APPROVED** [review]

**Comment by ratnesh-maurya** [comment]
Will merge it soon

**Pull request merged**
