### PR TITLE
Added Appointment Form Added with Form Validation to the doctor page

### PR DESCRIPTION
**Pull request by IkkiOcean**
### Description:
This pull request introduces a new appointment booking form to the **Rehabify** frontend, along with client-side form validation to ensure proper data input. The form allows users to book appointments with doctors while validating fields such as name, email, phone number, and appointment date.

- Closes : #103 
---

### Changes Implemented:
1. **Appointment Form**:
   - Added an appointment form with the following fields:
     - **Name** (Text input)
     - **Email** (Email input)
     - **Phone Number** (Number input)
     - **Appointment Date** (Date input)
     - **Submit Button**

2. **Form Validation**:
   - Implemented validation for all form fields to ensure accurate data submission:
     - **Name**: Required, must contain at least 3 characters.
     - **Email**: Must be a valid email address.
     - **Phone Number**: Must be exactly 10 digits.
     - **Appointment Date**: Must not be in the past.
   - Error messages are displayed below each input field if validation fails.

3. **Form Submission**:
   - If all validations pass, a success message is displayed
   - If any validations fail, appropriate error messages are shown and form submission is prevented.

---

### Preview:

https://github.com/user-attachments/assets/7f49e808-ebef-4e12-8395-a85e231ac620

### CODE REVIEW

**Comment by IkkiOcean** [comment]
@ratnesh-maurya please review and merge soon

**Comment by ratnesh-maurya** [comment]
will review by evening

**Comment by ratnesh-maurya** [comment]
hi @IkkiOcean  the input field doesn`t match with  ui on website and its not looking good

**Comment by IkkiOcean** [comment]
@ratnesh-maurya done! improved input field look and validation error message.
Screenshot 2024-10-19 at 11 35 15 PM

**Comment by ratnesh-maurya** [comment]
please try to use the existing components  see the other input field and try to use that

**Comment by IkkiOcean** [comment]
Screenshot 2024-10-20 at 8 52 45 PM

done! @ratnesh-maurya

**Comment by IkkiOcean** [comment]
Screenshot 2024-10-20 at 9 00 53 PM
done! @ratnesh-maurya used the Input Component which was already present in the project

**Comment by ratnesh-maurya** [comment]
Good work @IkkiOcean

**Pull request merged**
