### PR TITLE
Update User API migration and Postgresql DB

### PR DESCRIPTION
**Pull request by mienpham04**

### CODE REVIEW

**Comment by ratnesh-maurya** [comment]
hi @mienpham04 raise pr for migrate db branch

**Review by ratnesh-maurya — APPROVED** [review]

**Comment by MastanSayyad** [comment]
@ratnesh-maurya kindly give labels fairly

**Comment by ratnesh-maurya** [comment]
Hi @MastanSayyad , is there any issue with the lables

**Comment by MastanSayyad** [comment]
No worries, it happens.

**Pull request merged**
