### PR TITLE
fix: fixed the responsivness over required sections issue#50

### PR DESCRIPTION
**Pull request by syedfardeenjeelani**
i have fixed the responsiveness of all the required sections issue#50

### CODE REVIEW

**Comment by ratnesh-maurya** [comment]
Can you send me pictures how ui looked before and after the changes

**Comment by syedfardeenjeelani** [comment]
> Can you send me pictures how ui looked before and after the changes

@ratnesh-maurya  sure i will  share the video of the before and after ui

**Comment by syedfardeenjeelani** [comment]
@ratnesh-maurya 

https://github.com/user-attachments/assets/5bed0afe-a8c4-4d22-a9f0-f5c8c51ed4b5


https://github.com/user-attachments/assets/139c25e3-0914-4136-a8a3-68f928768c58

**Comment by ratnesh-maurya** [comment]
good work @syedfardeenjeelani

**Comment by syedfardeenjeelani** [comment]
@ratnesh-maurya  thanks

**Pull request merged**
