### PR TITLE
The implementation of a Testimonial card feature. (Issue #129)

### PR DESCRIPTION
**Pull request by RabdeepKaur**
Here I have added 3 testimonal card from an indiviual ,  a doctor and an organization  covering all the user target by the website .

after merge result:

https://github.com/user-attachments/assets/fac6d773-4e68-400d-a584-31edd5f254e5

### CODE REVIEW

**Comment by ratnesh-maurya** [comment]
Busy in some work will review it Tomorrow

**Comment by ratnesh-maurya** [comment]
Can you try to use the existing card available because on dark mode it should change color

**Comment by ratnesh-maurya** [comment]
yes

**Comment by RabdeepKaur** [comment]
hey @ratnesh-maurya  i did  use the card componenet  present in the code and  this is the result 

https://github.com/user-attachments/assets/e14da471-8018-4cc7-99d1-e119eb11d70e


 let me know what you think  and after that i will raise the PR

**Comment by ratnesh-maurya** [comment]
Looks good to me,  see if you can adjust photo's in someway  currently not looking that much good but we can have PR I can review and merge it

**Comment by RabdeepKaur** [comment]
I tried resizing the image, but it's not looking good because of the overall card structure.  and I raised the PR review it and let me know.

**Pull request merged**
