### PR TITLE
Add GitHub Action for linting, testing, and building TypeScript project

### LINKED ISSUE #126: Implement PR Issue Checker Workflow
**Description:** We need to create a GitHub Actions workflow that automates the validation of pull requests (PRs). This workflow will ensure that all PRs meet the following criteria before being merged:

**PR Description Check:** Every PR must have a description. If the description is missing, the PR should fail the check.
    
**Issue Reference Check:** The PR description must include an issue reference in the format Fixes #<issue-number>. If the PR is not addressing an existing issue, it should mention Fixes #NEW as a placeholder.

**Acceptance Criteria:**

- A GitHub Action workflow is triggered on PR events (opened, edited).

**The workflow checks the PR body for:**
- A non-empty description.
- The presence of Fixes #<issue-number> or Fixes #NEW.

**If the criteria are not met:**

- The workflow should fail and return clear error messages.

**If the checks pass:**
- A confirmation message is outputted.

**Expected Output:**

- Error message if the PR description is missing.
- Error message if the issue reference is missing or incorrectly formatted.
- Success message when all checks are satisfied.

**Additional Notes:**

- This issue may serve as a foundation for more advanced PR validation (e.g., commit message format, label enforcement).
- We can later extend this to check for specific branch naming conventions or enforce the addition of specific labels.

_**Note**_: i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!

@ratnesh-maurya

### PR DESCRIPTION
**Pull request by smog-root**
Closes #126 

**CI_LINT.yaml** :

**Working PROOF** :
**_It show's what are the errors in files ⬇_**

Screenshot (32)

This PR introduces a comprehensive Continuous Integration (CI) workflow using GitHub Actions to automate the following tasks for the TypeScript project:

- Linting: Ensures that the code follows the defined style and best practices.
- Testing: Runs the project’s test suite to validate code functionality.
- Building: Compiles the TypeScript code to ensure there are no type errors and generates the final JavaScript output.

**Details of Workflow:**

**Trigger Conditions:**

The workflow will automatically trigger on:

- Push events to the main branch.
- Pull requests targeting the main branch.

**Jobs:**

**Linting (ESLint):**

- Lints all TypeScript files (.ts and .tsx) in the project using ESLint.
- This ensures that all code adheres to the project's coding standards and best practices.

**Building (TypeScript Compiler):**

- Compiles the TypeScript code using the TypeScript compiler (tsc) to check for any type errors and ensure that the project builds successfully.
- The compiled output is stored in the dist directory (as specified in tsconfig.json).

**Testing (Jest):**

- Runs the test suite using Jest to validate that the code behaves as expected.
- Ensures that no new changes break existing functionality.

**Steps Performed in the Workflow:**
        
- Checkout the code from the repository using actions/checkout@v3.
- Set up Node.js using actions/setup-node@v3 with the specified Node.js version (16.x).
- Install dependencies via npm install.
- Run ESLint to check for linting issues using npm run lint.
- Compile TypeScript code using npm run build.
- Run Jest tests using npm test.

<hr>

**pr-checker.yaml** :

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`Fixes , Close, Closes, Closed , Fix , Fixed , Resolve , Resolves #Issue_number`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@ratnesh-maurya

### CODE REVIEW

**Comment by smog-root** [comment]
Update it to level3. It deserves it! @ratnesh-maurya

**Comment by ratnesh-maurya** [comment]
Will review Tomorrow

**Comment by smog-root** [comment]
@ratnesh-maurya did you review??

**Comment by ratnesh-maurya** [comment]
yes , can you try to use an AI-agent to review code 
https://medium.com/@akshayballal95/i-used-codiumais-pr-agent-and-i-love-it-6c1febad35b3

Like this

**Comment by smog-root** [comment]
@ratnesh-maurya merge it!

**Comment by ratnesh-maurya** [comment]
haave you done changes what i asked for

**Comment by smog-root** [comment]
@ratnesh-maurya you didn't say me anything!! you told "can you try to use an AI-agent to review code"!!

what should i change??

did you test it??

it's working perfectly fine!!

**Comment by ratnesh-maurya** [comment]
I have reviewed pr and asked for changes read the comments in the pr

**Comment by smog-root** [comment]
There are no change requests ??

**Comment by smog-root** [comment]
What should I add?? Tell now??!!

**Comment by ratnesh-maurya** [comment]
> @ratnesh-maurya you didn't say me anything!! you told "can you try to use an AI-agent to review code"!!
> 
> what should i change??
> 
> did you test it??
> 
> it's working perfectly fine!!?

Also I have mentioned there to implement code quality check ( which can be done through ai agent) and lint check only for more refer to comment in issue

**Comment by ratnesh-maurya** [comment]
> There are no change requests ??

let me see why its not showing up

**Review by ratnesh-maurya — CHANGES_REQUESTED** [review]

**Comment by smog-root** [comment]
Bro. I'm currently not going to work on this PR!! because I have done a lot of contributions about workflows!! A mod had warned me about doing this!

I told to the mod that I'm going to work on really stuff form now on.

He decreased my points on the leaderboard board and PR too!

Sorry. I can't implement more features to this PR!! If possible merge this PR. I have added linting @ratnesh-maurya

**Comment by ratnesh-maurya** [comment]
no issues

**Pull request closed without merging**
