### PR TITLE
fixed the cards layout and made it consistent on all pages #62

### PR DESCRIPTION
**Pull request by syedfardeenjeelani**
Fixed the issue where navigating from Page 1 to Page 2 caused a noticeable shift in the spacing between items. #62 

https://github.com/user-attachments/assets/46ecc8c4-01b2-495b-88c0-177bebba4b51

https://github.com/user-attachments/assets/658af19b-2069-47cd-90f4-d730ac0487d5

requesting a review @ratnesh-maurya

### CODE REVIEW

**Comment by ratnesh-maurya** [comment]
Will review Tomorrow

**Comment by syedfardeenjeelani** [comment]
> Will review Tomorrow

sure @ratnesh-maurya

**Comment by ratnesh-maurya** [comment]
yes , working fine , can you try to increase gap between cards

**Comment by syedfardeenjeelani** [comment]
@ratnesh-maurya sure

**Comment by syedfardeenjeelani** [comment]
> yes , working fine , can you try to increase gap between cards

increased gap between cards

image

**Comment by ratnesh-maurya** [comment]
good

**Review by ratnesh-maurya — APPROVED** [review]

**Comment by syedfardeenjeelani** [comment]
> good

thank you

**Pull request merged**
